-- ==========================================
-- DENUNCIA POPULAR - DATABASE SCHEMA
-- ==========================================

-- 1. FEEDBACK TABLE
create table if not exists feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text check (type in ('bug', 'suggestion', 'other')) not null,
  url text,
  user_agent text,
  timestamp text
);

-- 2. DENUNCIAS (REPORTS) TABLE
create table if not exists denuncias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  folio text unique not null,
  is_anonymous boolean default false,
  full_name text,
  email text,
  description text not null,
  category text,
  lat double precision,
  lng double precision,
  address text,
  competency text,
  legal_basis text,
  summary text,
  age text,
  gender text,
  occupation text,
  referral_source text,
  status text default 'PENDING',
  evidence_urls text[],
  user_id uuid references auth.users(id)
);

-- 3. TRIGGERS
-- Auto-populate user_id on insert
CREATE OR REPLACE FUNCTION set_user_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.user_id := auth.uid();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS set_user_id_on_insert ON denuncias;

CREATE TRIGGER set_user_id_on_insert
BEFORE INSERT ON denuncias
FOR EACH ROW
EXECUTE FUNCTION set_user_id();
