-- ==========================================
-- 1. TABLES SETUP
-- ==========================================

-- Create 'feedback' table if it doesn't exist
CREATE TABLE IF NOT EXISTS feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text check (type in ('bug', 'suggestion', 'other')) not null,
  url text,
  user_agent text,
  timestamp text
);

-- Create 'denuncias' table if it doesn't exist
CREATE TABLE IF NOT EXISTS denuncias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  folio text unique not null,
  is_anonymous boolean default false,
  full_name text,
  email text,
  description text not null,
  category text,
  lat double precision,
  lng double precision,
  address text,
  competency text,
  legal_basis text,
  summary text,
  age text,
  gender text,
  occupation text,
  referral_source text,
  status text default 'PENDING',
  evidence_urls text[]
);

-- ==========================================
-- 2. STORAGE SETUP
-- ==========================================

-- Create the 'evidence' bucket for file storage
INSERT INTO storage.buckets (id, name, public)
VALUES ('evidence', 'evidence', true)
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 3. SECURITY POLICIES (RLS)
-- ==========================================

-- Enable RLS on tables
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE denuncias ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to insert feedback
DROP POLICY IF EXISTS "Enable insert for everyone" ON feedback;
CREATE POLICY "Enable insert for everyone" ON feedback FOR INSERT WITH CHECK (true);

-- Policy: Allow anyone to insert denuncias
DROP POLICY IF EXISTS "Enable insert for everyone" ON denuncias;
CREATE POLICY "Enable insert for everyone" ON denuncias FOR INSERT WITH CHECK (true);

-- Storage Policies
-- Allow public read access (viewing evidence)
DROP POLICY IF EXISTS "Public Access Evidence" ON storage.objects;
CREATE POLICY "Public Access Evidence" ON storage.objects FOR SELECT USING ( bucket_id = 'evidence' );

-- Allow public upload access (anonymous users)
DROP POLICY IF EXISTS "Public Upload Evidence" ON storage.objects;
CREATE POLICY "Public Upload Evidence" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'evidence' );

-- ==========================================
-- 4. CLEANUP (Optional)
-- ==========================================
-- If you had previous policies with different names, you might want to check them in the dashboard.
