-- Create a table for storing feedback
create table feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text check (type in ('bug', 'suggestion', 'other')) not null,
  url text,
  user_agent text,
  timestamp text
);

-- Set up Row Level Security (RLS)
alter table feedback enable row level security;

-- Allow anyone (anon) to insert feedback
create policy "Enable insert for everyone"
on feedback for insert
with check (true);

-- Allow only authenticated users (admins) to view feedback
-- Note: You'll need to be logged in to the Supabase dashboard to see the data, 
-- or implement authentication in your app to view it.
create policy "Enable read access for authenticated users only"
on feedback for select
to authenticated
using (true);
